'use client';
import { useState } from 'react';
export default function Home() {
  const [start, setStart] = useState('');
  const [end, setEnd] = useState('');
  const [vehicle, setVehicle] = useState('Tesla Model Y');
  const [battery, setBattery] = useState(80);
  const [result, setResult] = useState(null);
  const handlePlanRoute = async (e) => {
    e.preventDefault();
    const res = await fetch('/api/route-plan', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ start, end, vehicle, battery }) });
    setResult(await res.json());
  };
  return (<main className="min-h-screen bg-gradient-to-b from-green-50 to-white dark:from-gray-900 dark:to-gray-800 p-6"><div className="max-w-4xl mx-auto"><div className="bg-gradient-to-br from-green-700 to-green-800 text-white p-8 rounded-xl mb-8 relative overflow-hidden shadow-lg"><div className="absolute right-6 top-4 text-6xl opacity-10">⚡</div><h1 className="text-4xl font-bold mb-2">LadeRute.no</h1><p className="text-lg opacity-90">Planlegg elbiltur med smarte ladepauser — uten stress</p></div><form onSubmit={handlePlanRoute} className="bg-white dark:bg-gray-800 p-8 rounded-xl shadow-md mb-8 border border-gray-200 dark:border-gray-700"><h2 className="text-2xl font-bold mb-6 text-gray-900 dark:text-white">Planlegg din tur</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4"><input type="text" placeholder="Fra (f.eks. Trondheim)" value={start} onChange={(e) => setStart(e.target.value)} className="p-3 border rounded-lg dark:bg-gray-700 dark:text-white" required /><input type="text" placeholder="Til (f.eks. Oslo)" value={end} onChange={(e) => setEnd(e.target.value)} className="p-3 border rounded-lg dark:bg-gray-700 dark:text-white" required /></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6"><select value={vehicle} onChange={(e) => setVehicle(e.target.value)} className="p-3 border rounded-lg dark:bg-gray-700 dark:text-white"><option>Tesla Model Y</option><option>VW ID.4</option><option>Kia EV6</option><option>Hyundai Ioniq 5</option><option>BMW i4</option></select><div><label className="block text-sm font-medium mb-2">Batteri: {battery}%</label><input type="range" min="10" max="100" value={battery} onChange={(e) => setBattery(parseInt(e.target.value))} className="w-full" /></div></div><button type="submit" className="w-full bg-green-700 hover:bg-green-800 text-white font-bold py-3 rounded-lg transition">Planlegg rute</button></form>{result && (<div className="bg-white dark:bg-gray-800 p-8 rounded-xl shadow-md border border-gray-200 dark:border-gray-700"><h2 className="text-2xl font-bold mb-6 text-gray-900 dark:text-white">Din rute</h2><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><div className="bg-green-50 dark:bg-gray-700 p-6 rounded-lg"><p className="text-gray-600 dark:text-gray-400 text-sm">Distanse</p><p className="text-3xl font-bold text-green-700 dark:text-green-400">{result.distance || '—'} km</p></div><div className="bg-blue-50 dark:bg-gray-700 p-6 rounded-lg"><p className="text-gray-600 dark:text-gray-400 text-sm">Ladetid</p><p className="text-3xl font-bold text-blue-700 dark:text-blue-400">{result.chargingTime || '—'} min</p></div><div className="bg-amber-50 dark:bg-gray-700 p-6 rounded-lg"><p className="text-gray-600 dark:text-gray-400 text-sm">Kostnad</p><p className="text-3xl font-bold text-amber-700 dark:text-amber-400">{result.cost || '—'} kr</p></div></div></div>)}</div></main>);